/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\gitMar\\Bayn-Web.github.io\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-304485ac",
    path: "/b_input/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-304485ac").then(next)
    },
  },
  {
    path: "/b_input/index.html",
    redirect: "/b_input/"
  },
  {
    name: "v-4c6a40fb",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c6a40fb").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-33a7859a",
    path: "/b_input/chapter1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33a7859a").then(next)
    },
  },
  {
    name: "v-2c8b2e1e",
    path: "/b_input/chapter2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c8b2e1e").then(next)
    },
  },
  {
    name: "v-02df1b88",
    path: "/part2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02df1b88").then(next)
    },
  },
  {
    path: "/part2/index.html",
    redirect: "/part2/"
  },
  {
    name: "v-21c982d7",
    path: "/part2/chapter1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21c982d7").then(next)
    },
  },
  {
    name: "v-1f7fea55",
    path: "/part2/chapter2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f7fea55").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]