/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/b_input/",
      "relativePath": "b_input/Readme.md",
      "key": "v-304485ac",
      "path": "/b_input/"
    },
    {
      "title": "b_input#",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "Readme.md",
      "key": "v-4c6a40fb",
      "path": "/"
    },
    {
      "title": "效果图 ##",
      "frontmatter": {},
      "regularPath": "/b_input/chapter1.html",
      "relativePath": "b_input/chapter1.md",
      "key": "v-33a7859a",
      "path": "/b_input/chapter1.html",
      "headers": [
        {
          "level": 2,
          "title": "效果图",
          "slug": "效果图"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "属性以及插槽",
          "slug": "属性以及插槽"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/b_input/chapter2.html",
      "relativePath": "b_input/chapter2.md",
      "key": "v-2c8b2e1e",
      "path": "/b_input/chapter2.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/part2/",
      "relativePath": "part2/Readme.md",
      "key": "v-02df1b88",
      "path": "/part2/"
    },
    {
      "frontmatter": {},
      "regularPath": "/part2/chapter1.html",
      "relativePath": "part2/chapter1.md",
      "key": "v-21c982d7",
      "path": "/part2/chapter1.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/part2/chapter2.html",
      "relativePath": "part2/chapter2.md",
      "key": "v-1f7fea55",
      "path": "/part2/chapter2.html"
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "input",
        "path": "/b_input/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          [
            "/b_input/chapter1",
            "登录输入框"
          ],
          [
            "/b_input/chapter2",
            "输入框"
          ]
        ]
      },
      {
        "title": "part2",
        "children": [
          "/part2/",
          "/part2/chapter1",
          "/part2/chapter2"
        ]
      }
    ]
  }
}